apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2  # Number of pods you want to run (scale as needed)
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: emsregistery.azurecr.io/dhanasekhar716/backendss:latest  # Replace with your image and tag
          ports:
            - containerPort: 8081  # Make sure this matches the port your app listens on
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # If you're using Spring profiles, set it as per your needs
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: /actuator/health  # Example for Spring Boot apps, adjust as needed
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health  # Example for Spring Boot apps, adjust as needed
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 20
