apiVersion: v1
kind: Service
metadata:
  name: spring-boots
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80          # External port for the service (exposed externally)
      targetPort: 8082   # The internal port your app listens on inside the container
  type: LoadBalancer
