name: Build and Deploy to AKS

on:
  push:
    branches:
      - main  # Trigger this workflow on pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check ACR credentials (debugging)
        run: |
          echo "ACR_USERNAME: ${{ secrets.ACR_USERNAME }}"
          echo "ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}"

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2  # Changed to the latest version
        with:
          login-server: emsregistery.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t emsregistery.azurecr.io/dhanasekhar716/backendss:latest .
          docker push emsregistery.azurecr.io/dhanasekhar716/backendss:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          kubeconfig: ${{ secrets.AKS_KUBECONFIG }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml


