name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java (if it's a Java-based project, adjust as needed)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Use your Java version here

      # Build the application using Maven (or Gradle, adjust as necessary)
      - name: Build with Maven
        run: mvn clean install  # Ensure the target/ems-backend-0.0.1-SNAPSHOT.jar file is created

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: emsregistery.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t emsregistery.azurecr.io/dhanasekhar716/backendss:$IMAGE_TAG .
          docker push emsregistery.azurecr.io/dhanasekhar716/backendss:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          kubeconfig: ${{ secrets.AKS_KUBECONFIG }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/your-deployment-name


